<?php

return array (
  'name' => 'DataBase',
  'beian' => '',
  'cdnurl' => '',
  'version' => '1.0.1',
  'timezone' => 'Asia/Shanghai',
  'forbiddenip' => '',
  'languages' => 
  array (
    'backend' => 'zh-cn',
    'frontend' => 'zh-cn',
  ),
  'fixedpage' => 'dashboard',
  'categorytype' => 
  array (
    'default' => 'Default',
    'page' => 'Page',
    'article' => 'Article',
    'test' => 'Test',
  ),
  'configgroup' => 
  array (
    'basic' => 'Basic',
    'email' => 'Email',
    'dictionary' => 'Dictionary',
    'user' => 'User',
    'example' => 'Example',
    'tags' => '标签配置',
  ),
  'mail_type' => '1',
  'mail_smtp_host' => 'smtp.qq.com',
  'mail_smtp_port' => '465',
  'mail_smtp_user' => '10000',
  'mail_smtp_pass' => 'password',
  'mail_verify_type' => '2',
  'mail_from' => '10000@qq.com',
  'tagsShow' => '[{"channel": 7,"name": "门户通知","type_id": 0, "enabled":{"guest": true, "student": true, "teacher": true}},
{"channel": 55,"name": "常用信息","type_id": 0, "enabled":{"guest": true, "student": true, "teacher": true}},
{"channel": 4,"name": "官网新闻","type_id": 0 ,"enabled":{"guest": true, "student": true, "teacher": true}},
{"channel": 3,"name": "易班","type_id": 0 ,"enabled":{"guest": true, "student": true, "teacher": true}},
{"channel": 5,"name": "先锋家园","type_id": 0 ,"enabled":{"guest": true, "student": true, "teacher": true}},
{"tag": "专题头条","name": "专题头条","type_id": 1 ,"enabled":{"guest": true, "student": true, "teacher": true}},
{"tag": "公告通知","name": "公告通知","type_id":1,"enabled":{"guest": true, "student": true, "teacher": true}},
{"tag": "活动预告","name": "活动预告","type_id": 1 ,"enabled":{"guest": true, "student": true, "teacher": true}},
{"tag": "信息","name": "信息学院","type_id": 2 ,"enabled":{"guest": true, "student": true, "teacher": true}},
{"tag": "公路","name": "公路学院","type_id": 2 ,"enabled":{"guest": true, "student": true, "teacher": true}},
{"tag": "汽车","name": "汽车学院","type_id": 2 ,"enabled":{"guest": true, "student": true, "teacher": true}},
{"tag": "公管","name": "公管学院","type_id": 2 ,"enabled":{"guest": true, "student": true, "teacher": true}},
{"tag": "建筑","name": "建筑学院","type_id": 2 ,"enabled":{"guest": true, "student": true, "teacher": true}},
{"tag": "建工","name": "建工学院","type_id": 2 ,"enabled":{"guest": true, "student": true, "teacher": true}},
{"tag": "外语","name": "外语学院","type_id": 2 ,"enabled":{"guest": true, "student": true, "teacher": true}},
{"tag": "地测","name": "地测学院","type_id": 2 ,"enabled":{"guest": true, "student": true, "teacher": true}},
{"tag": "理学院","name": "理学院","type_id": 2 ,"enabled":{"guest": true, "student": true, "teacher": true}},
{"tag": "电控","name": "电控学院","type_id": 2 ,"enabled":{"guest": true, "student": true, "teacher": true}},
{"tag": "经管","name": "经管学院","type_id": 2 ,"enabled":{"guest": true, "student": true, "teacher": true}},
{"tag": "公路","name": "公路学院","type_id": 2 ,"enabled":{"guest": true, "student": true, "teacher": true}},
{"tag": "资源","name": "资源学院","type_id": 2 ,"enabled":{"guest": true, "student": true, "teacher": true}},
{"tag": "环工","name": "环工学院","type_id": 2 ,"enabled":{"guest": true, "student": true, "teacher": true}},
{"tag": "材料","name": "材料学院","type_id": 2 ,"enabled":{"guest": true, "student": true, "teacher": true}},
{"tag": "文传","name": "文传学院","type_id": 2 ,"enabled":{"guest": true, "student": true, "teacher": true}},
{"tag": "马克思主义学院","name": "马克思主义学院","type_id": 2 ,"enabled":{"guest": true, "student": true, "teacher": true}},
{"tag": "机械","name": "机械学院","type_id": 2 ,"enabled":{"guest": true, "student": true, "teacher": true}}
]
',
);